#-*- coding: utf-8 -*-                                                                                                                                  
import requests
import time
import codecs
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
from xml.dom import minidom

def get_time(times):
    # 将时间戳转换为指定格式
    return time.strftime("%Y%m%d%H%M%S", time.localtime(int(times)))

def get_15_days():
    # 获取过去7天 + 今天 + 未来7天，共15天的日期列表
    days = []
    today = datetime.today()
    for i in range(-7, 8):
        target_date = today + timedelta(days=i)
        days.append(target_date.strftime('%Y%m%d'))
    return days

def saveXML(root, filename, indent="\t", newl="\n", encoding="utf-8"):
    rawText = ET.tostring(root)
    dom = minidom.parseString(rawText)
    with codecs.open(filename, 'w', 'utf-8') as f:
        dom.writexml(f, "", indent, newl, encoding)

# 你提供的最新频道列表
new_channel_list = [
    'cctv1', 'cctv2', 'cctv3', 'cctv4', 'cctveurope', 'cctvamerica', 'cctv5',
    'cctv5plus', 'cctv6', 'cctv7', 'cctv8', 'cctvjilu', 'cctv10', 'cctv11',
    'cctv12', 'cctv13', 'cctvchild', 'cctv15', 'cctv16', 'cctv17','cctv4k','cctv8k',
    'shijiedili', 'dianshigouwu', 'guofang', 'taiqiu', 'jingpin', 'shishang',
    'cctvyule', 'hjjc', 'cctvxiqu', 'xinkedongman', 'cctvqixiang', 'zhinan',
    'diyijuchang', 'cctvlaogushi', 'fyjc', 'cctvfyzq', 'fyyy', 'cctvgaowang'
]

def fetch_and_build_xml(ch_list):
    url = "http://api.cntv.cn/epg/epginfo"
    days = get_15_days()

    # 初始化数据存储字典
    channels_info = {} # 存储频道ID对应的频道名称
    programs_info = {ch: [] for ch in ch_list} # 存储频道对应的所有节目单

    # 将频道列表分块（每组20个），防止 GET 请求 URL 过长导致报错
    chunk_size = 20
    ch_chunks = [ch_list[i:i + chunk_size] for i in range(0, len(ch_list), chunk_size)]

    print(f"开始抓取 {len(days)} 天的EPG数据，总频道数：{len(ch_list)}...")

    for chunk in ch_chunks:
        ch_str = ",".join(chunk)
        for d in days:
            pay_dict = {"c": ch_str, "d": d}
            try:
                r = requests.get(url, params=pay_dict, timeout=10)
                # 直接解析 JSON
                programme_dict = r.json()
                
                # 处理获取到的数据放入内存
                for ch_id, items in programme_dict.items():
                    if ch_id not in channels_info and "channelName" in items:
                        channels_info[ch_id] = items["channelName"]
                        
                    if "program" in items:
                        for prog in items["program"]:
                            programs_info[ch_id].append({
                                'title': prog['t'],
                                'start': prog['st'],
                                'end': prog['et']
                            })
                print(f"成功抓取: {d} - 部分频道EPG数据...")
            except Exception as e:
                print(f"抓取失败 [日期:{d}, 频道:{ch_str}]: {e}")
            
            # 短暂休眠，防止请求过于频繁被API封禁
            time.sleep(0.3)

    # ---------------- 开始构建 XML ----------------
    root = ET.Element('tv')
    root.set("generator-info-name", "Generated by hyx2230")
    root.set("generator-info-url", "https://github.com/02720/EPG")

    # 步骤 1: 必须先按标准格式输出所有的 <channel> 频道定义标签
    for ch_id in ch_list:
        child = ET.SubElement(root, 'channel')
        child.set("id", ch_id)
        
        child_name = ET.SubElement(child, "display-name")
        child_name.set("lang", "zh")
        # 如果API中获取到了频道名则使用，否则默认使用频道ID
        child_name.text = channels_info.get(ch_id, ch_id)

    # 步骤 2: 按频道顺序依次输出所有的 <programme> 节目标签，并在单频道内部按时间排序
    for ch_id in ch_list:
        if ch_id in programs_info and programs_info[ch_id]:
            # 对该频道的所有节目按开始时间戳进行严格排序 (从过去到未来)
            sorted_progs = sorted(programs_info[ch_id], key=lambda x: x['start'])
            
            for prog in sorted_progs:
                starttime = get_time(prog['start'])
                endtime = get_time(prog['end'])

                programme_sub = ET.SubElement(root, "programme")
                programme_sub.set("start", starttime + " +0800")
                programme_sub.set("stop", endtime + " +0800")
                programme_sub.set("channel", ch_id)

                programme_title = ET.SubElement(programme_sub, "title")
                programme_title.set("lang", "zh")
                programme_title.text = prog['title']

    return root

if __name__ == '__main__':
    # 抓取并生成XML Tree
    xml_root = fetch_and_build_xml(new_channel_list)
    
    # 保存 XML
    print("正在保存 CCTV.xml ...")
    saveXML(xml_root, "CCTV.xml")
    print("完成！")
